- name: Flask_App
  hosts:  UAT-servers
  becom: yes
  gather_facts:
  tasks:

    - name: create a directory if it doesn't exist
      file:
        path: ~/flaskapp_V{{BUILD_NUMBER}}
        mode: 0755 


    - name: source from jenkinks's 
      copy: 
        src:  target/* 
        dest: ~/flask_app/flaskapp_V{{BUILD_NUMBER}}
    
    - name: Run `docker-compose up` again
      community.docker.docker_compose: 
        project_src: ~/flask_app/flaskapp_V{{BUILD_NUMBER}}
        files: 
        - compose.yml
    - name: verify fy the docker ps -a
      shell: docker ps -a