- name: Flask_App
  hosts:  UAT-servers
  gather_facts:
  vars:
    artifact_item: /var/lib/jenkins/workspace/ansible_docker-compose/santu_flask01/
  
  tasks:

    - name: create a directory if it doesn't exist
      file:
        path: ~/flask_app/flaskapp_V{{BUILD_NUMBER}}
        mode: 0755 
        state: directory
    - name: testing 
      copy: 
        src:  ~/flask_app/flask.zip
        dest: ~/flask_app/flaskapp_V{{BUILD_NUMBER}}
        remote_src: yes


    - name: verify fy the docker ps -a
      shell: docker ps 
    
    - name: Unarchive a file that is already on the remote machine
      shell: "cd ~/flask_app/flaskapp_V{{BUILD_NUMBER}}/; unzip flask.zip"

    - name: Run docker-compose up
      shell: docker-compose ~/flask_app/flaskapp_V{{BUILD_NUMBER}}/compose.yaml
       
        
      
