- name: Flask_App
  hosts:  UAT-servers
  gather_facts:
  tasks:

    - name: create a directory if it doesn't exist
      file:
        path: ~/flask_app/flaskapp_V{{BUILD_NUMBER}}
        mode: 0755 
        state: directory


    - name: source from jenkinks's 
      copy: 
        src:  /var/lib/jenkins/workspace/ansible_docker-compose/santu_flask01/flskapp_BUILD_NUMBER.zip
        dest: ~/flask_app/flaskapp_V{{BUILD_NUMBER}}/
        remote_src: true
        directory_mode: yes
    
    - name: Run `docker-compose up` again
      community.docker.docker_compose: 
        project_src: ~/flask_app/flaskapp_V{{BUILD_NUMBER}}
        files: 
        - compose.yml
    - name: verify fy the docker ps -a
      shell: docker ps -a